version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.1.0
workflows:
  deployment:
    jobs:
      - aws-ecr/build_and_push_image:
          context: ./client         
          dockerfile: ./client/Dockerfile
          path: ./client/Dockerfile
          profile-name: ecr-user #AWS profile name to be configured.
          repo: sample-flask #Name of an Amazon ECR repository
          tag: '${CIRCLE_SHA1}'
          # Uncomment if the repository does not yet exist
          # create-repo: true
      

     