version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
workflows:
  deployment:
    jobs:
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          path: ./client
          profile-name: ecr-user #AWS profile name to be configured.
          repo: sample-flask #Name of an Amazon ECR repository
          tag: 'latest,${CIRCLE_SHA1}'
          # Uncomment if the repository does not yet exist
          # create-repo: true
      

     